print('hello'.upper())
print('HAPPY BIRTHDAY!'.lower())
print('WeeeEEEEeeeEEEEeee'.swapcase())
print('ABC123'.isupper())
print('aeiouAEIOU'.count('a'))
print('hello'.endswith('o'))
print('hello'.startswith('H'))
print('Hello {0}!'.format('Python'))
print('Hello {0}! Hello {1}!'.format('Python','World'))

